version: '3.5'

services:
  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-service
    environment:
      - PORT=4003
    ports:
      - '4003:4003'
    volumes:
      - ./src:/app/src
      - /var/www/web/storage:/var/www/web/storage
    environment:
      - NODE_ENV=production
  