version: '3.5'

services:
  app:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-service
    environment:
      - PORT=4002
      - NODE_ENV=production
    ports:
      - '4002:4002'
    volumes:
      - ./src:/app/src
      - /var/www/web/storage:/var/www/web/storage
      
  